In [1]:
import pandas as pd
import numpy as np
import flask
import pymysql
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [4]:
# Restaurent reviews prediction systems
# #Sentiment Analysis of Restaurant Reviews

In [5]:
# owner >> cust >> text >> model >> good or bad >> analysis 
# food >> quality inrease
# kaggle

In [ ]:
# problem statement

In [6]:
# Normally, a lot of businesses are remained as failures due to lack of profit, lack of proper 
# improvement measures. Mostly, restaurant owners face a lot of difficulties to improve their productivity. 
# This project really helps those who want to increase their productivity, which in turn increases 
# their business profits. This is the main objective of this project.

# What the project does is that the restaurant owner gets to know about drawbacks of 
# his restaurant such as most disliked food items of his restaurant by customer’s text 
# review which is processed with ML classification algorithm(Naive Bayes)

# The purpose of this analysis is to build a prediction model to predict whether 
# a review on the restaurant is positive or negative. To do so, we will work on Restaurant Review dataset, 
# we will load it into predicitve algorithms Multinomial Naive Bayes, Bernoulli Naive Bayes and 
# Logistic Regression. In the end, we hope to find a "best" model for predicting the review's sentiment.

In [7]:
# Dataset: Restaurant_Reviews.tsv is a dataset from Kaggle datasets which consists of 
# 1000 reviews on a restaurant.

# To build a model to predict if review is positive or negative, following steps are performed.

# Importing Dataset
# Preprocessing Dataset
# Vectorization
# Training and Classification
# Analysis Conclusion

In [9]:
# Tools & Technologies Used:
# NLTK
# Machine Learning
# Python
# Tkinter
# Mysql
# Pandas
# flask
# git and github

In [10]:
# step-1 Data collection

In [2]:
import pandas as pd
import numpy as np
import flask
import pymysql
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [3]:
df=pd.read_csv('r_data.tsv',delimiter='\t')

In [4]:
df

,Review,Liked
0,Wow... Loved this place.,1
1,Crust is not good.,0
2,Not tasty and the texture was just nasty.,0
3,Stopped by during the late May bank holiday of...,1
4,The selection on the menu was great and so wer...,1
...,...,...
1381,clean,1
1382,less,0
1383,clean,1
1384,less,0


In [5]:
df.shape

(1386, 2)

In [6]:
# step-2 Data cleaning

In [7]:
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [8]:
df.dtypes

Review      str
Liked     int64
dtype: object

In [9]:
# 1 >> positive /Good
# 0 >> negative /Bad

In [10]:
# step-3 EDA / Text preprocessing/ML preprocessing

# remove stopwords
# stemming
# lowercase

In [11]:
X=df['Review']
y=df['Liked']

In [12]:
y.value_counts()

Liked
1    792
0    594
Name: count, dtype: int64

In [13]:
# dataset is balanced

In [14]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
import re

In [15]:
# lowercase

text='Hi how are you'
newtext=text.lower()
print(newtext)

hi how are you


In [16]:
# remove digit or special characters

text='Hi ^&# how 123 are you?'


newresult=re.sub(r'[^a-zA-Z\s]','',text)
print(newresult)

Hi  how  are you


In [17]:
# tokenization >> break down sentence into words 

text='Hi how are you'
list1=word_tokenize(text)
print(list1)

['Hi', 'how', 'are', 'you']


In [18]:
# remove stopwords
# stopwords >> most comman words >> ex a an the on this ...

nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[

True

In [24]:
s_list=stopwords.words('english')

In [25]:
len(s_list)

198

In [26]:
text='cat sat on mat and this is real problem'
list1=word_tokenize(text)
print(list1)

['cat', 'sat', 'on', 'mat', 'and', 'this', 'is', 'real', 'problem']


In [27]:
list2=[  i for i in list1 if i not in s_list]

In [28]:
list2

['cat', 'sat', 'mat', 'real', 'problem']

In [29]:
# stemming /lemmatization
# to get root word 
# to cut off suffixes


# affect affecting affected >> affect 

In [30]:
ps=PorterStemmer()
ps.stem('affected')

'affect'

In [31]:
# join

In [32]:
list1=['cat', 'sat', 'mat', 'real', 'problem']

In [33]:
finalstr=' '.join(list1)

In [34]:
finalstr

'cat sat mat real problem'

In [35]:
df['Review']

0                                Wow... Loved this place.
1                                      Crust is not good.
2               Not tasty and the texture was just nasty.
3       Stopped by during the late May bank holiday of...
4       The selection on the menu was great and so wer...
                              ...                        
1381                                                clean
1382                                                 less
1383                                                clean
1384                                                 less
1385                                                clean
Name: Review, Length: 1386, dtype: str

In [36]:
a='cat sat on mat'

In [37]:
a.split()

['cat', 'sat', 'on', 'mat']

In [38]:
import re

In [39]:
corpus=[]
for i in df['Review']:
    text=i.lower()
    text1=re.sub(r'[^a-zA-Z\s]','',text)
    list1=word_tokenize(text1)
    list2=[  i for i in list1 if i not in s_list]
    ps=PorterStemmer()
    list3=[  ps.stem(i) for i in list2]
    finalstr=' '.join(list3)
    corpus.append(finalstr)
      

In [41]:
corpus

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti didnt tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberrymmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'that rightth red velvet cakeohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'foun

In [54]:
# vectorization 
# text data to numeric form
# countvectoizer 

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()
y=df['Liked']

In [43]:
X.shape

(1386, 1611)

In [44]:
df.shape

(1386, 2)

In [45]:
cv.get_feature_names_out()

array(['absolut', 'absolutley', 'accid', ..., 'yum', 'yummi', 'zero'],
      shape=(1611,), dtype=object)

In [46]:
X_df=pd.DataFrame(X,columns=cv.get_feature_names_out())

In [47]:
X_df

,absolut,absolutley,accid,accommod,accomod,accordingli,account,ach,acknowledg,across,...,yelper,yet,youd,youll,your,yucki,yukon,yum,yummi,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1381,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1383,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1384,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [48]:
# train test split >> cross validation

In [49]:
# model training >> Logistic Regression ,Multinomial ,Bernoullies

In [50]:
# Training and Classification
# Further the data is splitted into training and testing set using Cross Validation technique. 
# This data is used as input to classification algorithm.

# Classification Algorithms:

# Algorithms like Decision tree, Support Vector Machine, Logistic Regression, 
# Naive Bayes were implemented and on comparing the evaluation metrics two of the algorithms 
# gave better predictions than others.

# Multinomial Naive Bayes
# Bernoulli Naive Bayes
# Logistic Regression

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_df,y,test_size=0.2,random_state=42)

In [52]:
#Multinomial NB

In [53]:
from sklearn.naive_bayes import MultinomialNB
classifier1= MultinomialNB()
classifier1.fit(X_train, y_train)

y_pred = classifier1.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
print('Classification Report\n', classification_report(y_test, y_pred))
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))

Confusion Matrix:
 [[ 87  33]
 [ 23 135]]
Classification Report
               precision    recall  f1-score   support

           0       0.79      0.72      0.76       120
           1       0.80      0.85      0.83       158

    accuracy                           0.80       278
   macro avg       0.80      0.79      0.79       278
weighted avg       0.80      0.80      0.80       278



Accuracy is  79.86 %
Precision is  0.8
Recall is  0.85


In [54]:
from sklearn.naive_bayes import BernoulliNB
classifier2= BernoulliNB()
classifier2.fit(X_train, y_train)

y_pred = classifier2.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
print('Classification Report\n', classification_report(y_test, y_pred))
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))

Confusion Matrix:
 [[ 78  42]
 [ 20 138]]
Classification Report
               precision    recall  f1-score   support

           0       0.80      0.65      0.72       120
           1       0.77      0.87      0.82       158

    accuracy                           0.78       278
   macro avg       0.78      0.76      0.77       278
weighted avg       0.78      0.78      0.77       278



Accuracy is  77.7 %
Precision is  0.77
Recall is  0.87


In [55]:
from sklearn.linear_model import LogisticRegression
classifier3= LogisticRegression()
classifier3.fit(X_train, y_train)

y_pred = classifier3.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
print('Classification Report\n', classification_report(y_test, y_pred))
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))

Confusion Matrix:
 [[ 96  24]
 [ 28 130]]
Classification Report
               precision    recall  f1-score   support

           0       0.77      0.80      0.79       120
           1       0.84      0.82      0.83       158

    accuracy                           0.81       278
   macro avg       0.81      0.81      0.81       278
weighted avg       0.81      0.81      0.81       278



Accuracy is  81.29 %
Precision is  0.84
Recall is  0.82


In [56]:
# Logistic regression >> 81.29%
# BernoulliNB >> 78%
# MultinomialNB >> 80%

In [57]:
# #Analysis and Conclusion

In [58]:
# In this study, an attempt has been made to classify sentiment analysis for restaurant reviews 
# using machine learning techniques. Two algorithms namely Multinomial Naive Bayes and 
# Bernoulli Naive Bayes are implemented.

# Evaluation metrics used here are accuracy, precision and recall.


# Using Multinomial Naive Bayes,
# Accuracy is  79.86 %
# Precision is  0.8
# Recall is  0.85


# Using Bernoulli Naive Bayes,
# Accuracy is  77.7 %
# Precision is  0.77
# Recall is  0.87


# Using Logistic Regression,
# Accuracy is  81.29 %
# Precision is  0.84
# Recall is  0.82


# From the above results, Logistic Regression is slightly better than Multinomial Naive Bayes

In [59]:
# final model >> Logistic regression

In [60]:
from sklearn.linear_model import LogisticRegression
classifier3= LogisticRegression()
classifier3.fit(X_df, y)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [61]:
import pickle

In [62]:
with open('lgmodel','wb') as f:
    pickle.dump(classifier3,f)

In [63]:
with open('cvmodel','wb') as f:
    pickle.dump(cv,f)

In [64]:
# new text prediction

In [92]:
a='not good taste'

In [93]:
newpredlist=[a]

In [94]:
a_cv=cv.transform(newpredlist).toarray()

In [95]:
a_cv

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 1611))

In [96]:
a_cv.shape

(1, 1611)

In [97]:
result=classifier3.predict(a_cv)

d:\WE_project\rest_ml_project\venv314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [98]:
result[0]

np.int64(1)

In [99]:
if 'not' in a.lower():
    result=abs(result[0]-1)
else:
    result=result[0]

In [100]:
result

np.int64(0)